packages:
  - 'frontend'
  - 'backend'
  - 'worker'
  - 'packages/*'

ignoredBuiltDependencies:
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - workerd
onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
